config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'

  resources :articles

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }

  has_many :articles

  validates :username, presence: true,  uniqueness: { case_sensitive: false }, length: {minimum: 3, maximum: 25 }

  VALID_EMAIL_FORMAT = /\A[a-z0-9\+\-_\.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true, uniqueness: { case_sensitive: false }, length: { maximum: 125 }, format: { with: VALID_EMAIL_FORMAT }

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def show
  end

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.user = User.first
    if @article.save
      flash[:notice] = 'Article was created sucessfully!'
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Sucessfully updated."
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private #everything below this is only usable in this script!

    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :description)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You are now logged in."
      redirect_to user_path(user)
    else
      flash.now[:danger] = "There was something wrong with your login details."
      render 'new'
    end

  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out."
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:sucess] = "Welcome to the Alpha Blog, #{@user.username}!"
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:sucess] = "Your account was updated sucessfully"
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def show
    @user = User.find(params[:id])

  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.username, class: "img-circle")
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Author</th>
      <th colspan='3'>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% obj.each do |a| %>
      <tr>
        <td><%= a.title %></td>
        <td><%= a.description %></td>
        <td><%= a.user.username %></td>
        <td><%= link_to 'Show', article_path(a) %></td>
        <td><%= link_to 'Edit', edit_article_path(a) %></td>
        <td><%= link_to 'Delete', article_path(a), method: :delete, data: { confirm: "Are  you sure" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
  <h2>The following errors prevented the article from being saved:</h2>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
  <% end %>
  </ul>
<% end %>


<%= form_with(model: @article, local: true) do |f| %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Cancel and return to index page', articles_path %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1>Articles listing page</h1>

<%= render 'article', obj: @articles %>

<p>
  <%= link_to 'Create new article', new_article_path %>
</p>

app/views/articles/new.html.erb
<h1>Submit a new article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h1>Showing articles here..</h1>

<p><strong>Title: </strong> <%= @article.title %></p>
<p><strong>Description: </strong> <%= @article.description %></p>
<p><strong>Author:</strong> <%= @article.user.username %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Delete', article_path(@article), method: :delete, data: { confirm: "Are  you sure"} %> |
<%= link_to 'Return to index page', articles_path %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <%= msg %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Alpha Blog", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Articles", articles_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Users</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">About</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-light my-2 my-sm-0" type="submit"  >Search</button>
    </form>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to 'Log out', logout_path, method: :delete %></li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%=  render 'layouts/navigation' %>
    <%=  render 'layouts/messages' %>
    <%= yield %>
  </body>

  <footer class="footer">
    <div class="container">
    <div class="copyright col-md-6">
  Copyright © 2020 - All rights reserved.</div>
    </div>
  </footer>
  
</html>

app/views/pages/about.html.erb
<h1>And this is the About page..:)</h1>

<%= link_to 'Check Article index page', articles_path %> |
<%= link_to 'Home page', root_path %> 

app/views/pages/home.html.erb
<div class="container" id="home-container">
  <div class="jumbotron">
    <h1 class="display-4">Alpha Blog!</h1>
    <p class="lead">Here goes a brief description of Alpha-Blog.</p>
    <hr class="my-4">
    <p>Here goes some more text with not as much importance.</p>
    <a class="btn btn-secondary btn-lg" href="#" role="button">Sign up!</a>
  </div>
</div>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <h2>The following errors prevented the user from being saved:</h2>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
  <% end %>
  </ul>
<% end %>


<%= form_with(model: @user, local: true) do |f| %>

  <p>
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </p>

  <p>
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </p>

  <p>
    <%= f.label :pasword %><br>
    <%= f.password_field :password %>
  </p>

  <p>
    <%= f.submit(@user.new_record? ? "Sign up" : "Update account") %>
  </p>
<% end %>

<%= link_to 'Cancel and return to index page', articles_path %>

app/views/users/edit.html.erb
<h1>Edit your account</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>All Alpha Bloggers</h1>
<% @users.each do |user| %>
  <ul class="listing">
    <div class="row">
      <div class="well col-md4 col-md-offset-4">
        <li><%= link_to gravatar_for(user), user_path(user) %></li>
        <li class="article-title">
          <%= link_to user.username, user_path(user) %>
        </li>
        <li><small><%= pluralize(user.articles.count, "article") if user.articles %></small></li>
      </div>
    </div>
  </ul>
<% end %>

app/views/users/new.html.erb
<h1>Sign up for Alpha Blog</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1> Welcome to <%= @user.username %>'s page</h1>
<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
    <%= gravatar_for @user %>
  </div>
</div>
<h4><%= @user.username %>'s articles</h4>
<%= render 'articles/article', obj: @user.articles %>